name: Update cached versions

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * 5'

env:
  DEPLOY_USER: "Kiran Kumar Kotari"
  DEPLOY_EMAIL: "kirankotari@live.com"
  DEPLOY_COMMIT_MESSAGE: Update cached versions
  DEPLOY_BRANCH: master


jobs:
  update_cache:
    runs-on: windows-latest
    env:
      HOME: D:/a/pyenv-win/pyenv-win
    steps:
    - name: Checkout master
      uses: actions/checkout@v3
    - name: Create a branch
      uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'automated/update_cache'
    - name: Invoke update
      run: ${{ env.HOME }}/pyenv-win/bin/pyenv.bat update
      shell: bash
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: ${{ env.DEPLOY_COMMIT_MESSAGE }} [skip ci]
        author: '${{ env.DEPLOY_USER }} <${{ env.DEPLOY_EMAIL }}>'
        title: '[Automated] ${{ env.DEPLOY_COMMIT_MESSAGE }}'
        body: |
          Automated Pull Request
          - Event Name: ${{ github.event_name }}
          - Event Type: ${{ github.event.action }}
          - Proudly Auto-generated using [create-pull-request][1]
          [1]: https://github.com/peter-evans/create-pull-request
        labels: automerge
        base: ${{ env.DEPLOY_BRANCH }}
        branch: automated/update_cache
