name: Update cached versions

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * 5'

env:
  DEPLOY_USER: "Kiran Kumar Kotari"
  DEPLOY_EMAIL: "kirankotari@live.com"
  DEPLOY_COMMIT_MESSAGE: Update cached versions
  DEPLOY_BRANCH: master


jobs:
  update_cache:
    runs-on: windows-latest
    env:
      HOME: D:/a/pyenv-win/pyenv-win
    steps:
    - name: Checkout master
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Update versions cache
      run: python ${{ env.HOME }}/.github/scripts/update_versions_cache.py
      shell: bash
    - name: Commit and push changes
      run: |
        git config user.name "${{ env.DEPLOY_USER }}"
        git config user.email "${{ env.DEPLOY_EMAIL }}"
        git checkout -b automated/update_cache
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        git commit -m "${{ env.DEPLOY_COMMIT_MESSAGE }} [skip ci]"
        git push -f origin automated/update_cache
      shell: bash
    - name: Create Pull Request
      run: |
        gh pr create --base ${{ env.DEPLOY_BRANCH }} \
          --head automated/update_cache \
          --title "[Automated] ${{ env.DEPLOY_COMMIT_MESSAGE }}" \
          --body "Automated Pull Request
        - Event Name: ${{ github.event_name }}
        - Event Type: ${{ github.event.action }}" \
          --label automerge || gh pr edit automated/update_cache \
          --title "[Automated] ${{ env.DEPLOY_COMMIT_MESSAGE }}" \
          --body "Automated Pull Request
        - Event Name: ${{ github.event_name }}
        - Event Type: ${{ github.event.action }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
